### ISSUE TITLE
ToDo 25/11/19

### ISSUE THREAD

**Issue by ballinc** [AnswerMeWithMrB/website#1]
### Welcome!
If you're here, you probably want to help out! Fork the repo and pick a task below. Once you're done, submit a pull request and, once approved, you will see your change appear on [answermewithmrb.tk](https://answermewithmrb.tk).

## No coding required
- [x] Add the rest of the video pages
- [ ] Write paragraph description of channel / site
- [ ] Design activities for each video
- [ ] Decide on gradient for subscribe, [use this tool](https://cssgradient.io/)

##  Coding required
**Easy**
- [ ] Favicon
- [ ] <title></title> on each page with liquid variables
- [ ] Review button colours

**Harder**
- [ ] Restyle video cards
  - [x] Remove underline for title
  - [x] Fix padding on card
  - [ ] Align thumbnail and video number
- [x] Move video description from {{ content }} to {{ page.description }}
- [x] Allow extra content in {{ content }} to display on video page
- [ ] Move quiz
- [ ] Setup quiz messages (for correct/wrong/full marks/no marks etc)
- [ ] Add quick links to playlists on videos page
- [ ] change #6 inline temp-fix to permanent styling

**Hardest**
- [ ] Add mobile styling
  - [ ] Fix previous / next / view more button placement on video pages
  - [ ] Fix YouTube embed sizings
  - [ ] Remove quiz padding
  - [ ] Restyle contact form button
- [ ] Make activities management easier
- [ ] Add new activities

**Much effort required for no visible difference**
- [ ] Migrate styling to scss

## Craig
- [ ] Google analytics?
- [x] Setup contact form
- [x] Setup contact page
- [x] Cloudflare
